import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const root = process.cwd();
const apiEnvPath = path.join(root, "apps", "api", ".env");
const webEnvPath = path.join(root, "apps", "web", ".env.local");

function exists(p) {
  try {
    fs.accessSync(p, fs.constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

function genHex(bytes) {
  return crypto.randomBytes(bytes).toString("hex");
}

function genBase64(bytes) {
  return crypto.randomBytes(bytes).toString("base64");
}

function writeIfMissing(filePath, content) {
  if (exists(filePath)) {
    console.log(`[skip] ${path.relative(root, filePath)} already exists`);
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
  console.log(`[write] ${path.relative(root, filePath)}`);
}

const apiEnv = `# Generated by scripts/setup-env.mjs
NODE_ENV=development
PORT=8090
CORS_ORIGIN=http://localhost:3000

# Dev default: no local install needed
MONGODB_URI=memory
# To use local MongoDB instead:
# MONGODB_URI=mongodb://127.0.0.1:27017/ai_medical_interpreter

JWT_ACCESS_SECRET=${genHex(48)}
JWT_REFRESH_SECRET=${genHex(48)}
JWT_ACCESS_TTL_MIN=30
JWT_REFRESH_TTL_DAYS=30

DATA_ENCRYPTION_KEY_BASE64=${genBase64(32)}

# Required for AI features:
OPENAI_API_KEY=
OPENAI_MODEL=gpt-4.1-mini

# Scanned PDF OCR (first N pages):
PDF_OCR_MAX_PAGES=3

# Upload storage:
STORAGE_DRIVER=local
# STORAGE_DRIVER=s3
# S3_BUCKET=
# S3_REGION=
# S3_ACCESS_KEY_ID=
# S3_SECRET_ACCESS_KEY=
# S3_ENDPOINT=

# Optional: email reminders
SENDGRID_API_KEY=
EMAIL_FROM=

# Optional: push notifications via FCM
FIREBASE_SERVICE_ACCOUNT_JSON=

# Admin bootstrap (comma-separated emails)
ADMIN_EMAILS=admin@example.com
`;

const webEnv = `# Generated by scripts/setup-env.mjs
NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:8090

# Optional: Firebase Cloud Messaging (push notifications)
NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
NEXT_PUBLIC_FIREBASE_APP_ID=
NEXT_PUBLIC_FIREBASE_VAPID_KEY=
`;

writeIfMissing(apiEnvPath, apiEnv);
writeIfMissing(webEnvPath, webEnv);

console.log("\nNext:");
console.log("- Add your OpenAI key to apps/api/.env (OPENAI_API_KEY=...)");
console.log("- Ensure MongoDB is running, then run: npm run dev");
